// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vemuuwizsgkqrceuwjdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbXV1d2l6c2drcXJjZXV3amRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzkyODUsImV4cCI6MjA2NTU1NTI4NX0.v-yFu_dt9wXaY-Lpbn1_D93VHW64eVywjIJBRGzXU7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);